// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_access_token_api_v1_login_access_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login_access_token_api_v1_login_access_token_post'
} as const;

export const Body_upload_to_db_api_v1_upload__postSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_upload_to_db_api_v1_upload__post'
} as const;

export const CreateReportSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        date_range_start: {
            type: 'string',
            format: 'date-time',
            title: 'Date Range Start'
        },
        date_range_end: {
            type: 'string',
            format: 'date-time',
            title: 'Date Range End'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        model_range: {
            type: 'string',
            title: 'Model Range'
        }
    },
    type: 'object',
    required: [
        'name',
        'date_range_start',
        'date_range_end',
        'model_range'
    ],
    title: 'CreateReport'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const OrdersSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        order_id: {
            type: 'integer',
            title: 'Order Id'
        },
        order_date: {
            type: 'string',
            format: 'date-time',
            title: 'Order Date'
        },
        product_sku: {
            type: 'string',
            title: 'Product Sku'
        },
        product_name: {
            type: 'string',
            title: 'Product Name'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        qty_ordered: {
            type: 'number',
            title: 'Qty Ordered'
        },
        model_range: {
            type: 'string',
            title: 'Model Range'
        }
    },
    type: 'object',
    required: [
        'order_id',
        'order_date',
        'product_sku',
        'product_name',
        'price',
        'qty_ordered',
        'model_range'
    ],
    title: 'Orders'
} as const;

export const OrdersPublicSchema = {
    properties: {
        order_id: {
            type: 'integer',
            title: 'Order Id'
        },
        order_date: {
            type: 'string',
            format: 'date-time',
            title: 'Order Date'
        },
        product_sku: {
            type: 'string',
            title: 'Product Sku'
        },
        product_name: {
            type: 'string',
            title: 'Product Name'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        qty_ordered: {
            type: 'number',
            title: 'Qty Ordered'
        },
        model_range: {
            type: 'string',
            title: 'Model Range'
        }
    },
    type: 'object',
    required: [
        'order_id',
        'order_date',
        'product_sku',
        'product_name',
        'price',
        'qty_ordered',
        'model_range'
    ],
    title: 'OrdersPublic'
} as const;

export const ReportPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        date_range_start: {
            type: 'string',
            format: 'date-time',
            title: 'Date Range Start'
        },
        date_range_end: {
            type: 'string',
            format: 'date-time',
            title: 'Date Range End'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        model_range: {
            type: 'string',
            title: 'Model Range'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_at',
        'date_range_start',
        'date_range_end',
        'model_range'
    ],
    title: 'ReportPublic'
} as const;

export const ReportPublicWithDataSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        date_range_start: {
            type: 'string',
            format: 'date-time',
            title: 'Date Range Start'
        },
        date_range_end: {
            type: 'string',
            format: 'date-time',
            title: 'Date Range End'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        model_range: {
            type: 'string',
            title: 'Model Range'
        },
        data: {
            items: {
                $ref: '#/components/schemas/OrdersPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_at',
        'date_range_start',
        'date_range_end',
        'model_range',
        'data'
    ],
    title: 'ReportPublicWithData'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        }
    },
    type: 'object',
    required: [
        'id',
        'username',
        'is_active',
        'is_superuser'
    ],
    title: 'UserPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
