// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AddReportApiV1ReportsPostData, AddReportApiV1ReportsPostErrors, AddReportApiV1ReportsPostResponses, GetOrdersApiV1OrdersGetData, GetOrdersApiV1OrdersGetErrors, GetOrdersApiV1OrdersGetResponses, GetReportIdApiV1ReportsReportIdGetData, GetReportIdApiV1ReportsReportIdGetErrors, GetReportIdApiV1ReportsReportIdGetResponses, LoginAccessTokenApiV1LoginAccessTokenPostData, LoginAccessTokenApiV1LoginAccessTokenPostErrors, LoginAccessTokenApiV1LoginAccessTokenPostResponses, ReadReportsApiV1ReportsGetData, ReadReportsApiV1ReportsGetResponses, RemoveReportApiV1ReportsReportIdDeleteData, RemoveReportApiV1ReportsReportIdDeleteErrors, RemoveReportApiV1ReportsReportIdDeleteResponses, TestTokenApiV1LoginTestTokenPostData, TestTokenApiV1LoginTestTokenPostResponses, UploadToDbApiV1UploadPostData, UploadToDbApiV1UploadPostErrors, UploadToDbApiV1UploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Login {
    /**
     * Login Access Token
     */
    public static loginAccessTokenApiV1LoginAccessTokenPost<ThrowOnError extends boolean = false>(options: Options<LoginAccessTokenApiV1LoginAccessTokenPostData, ThrowOnError>): RequestResult<LoginAccessTokenApiV1LoginAccessTokenPostResponses, LoginAccessTokenApiV1LoginAccessTokenPostErrors, ThrowOnError> {
        return (options.client ?? client).post<LoginAccessTokenApiV1LoginAccessTokenPostResponses, LoginAccessTokenApiV1LoginAccessTokenPostErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Test Token
     */
    public static testTokenApiV1LoginTestTokenPost<ThrowOnError extends boolean = false>(options?: Options<TestTokenApiV1LoginTestTokenPostData, ThrowOnError>): RequestResult<TestTokenApiV1LoginTestTokenPostResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).post<TestTokenApiV1LoginTestTokenPostResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/login/test-token',
            ...options
        });
    }
}

export class Upload {
    /**
     * Upload To Db
     */
    public static uploadToDbApiV1UploadPost<ThrowOnError extends boolean = false>(options: Options<UploadToDbApiV1UploadPostData, ThrowOnError>): RequestResult<UploadToDbApiV1UploadPostResponses, UploadToDbApiV1UploadPostErrors, ThrowOnError> {
        return (options.client ?? client).post<UploadToDbApiV1UploadPostResponses, UploadToDbApiV1UploadPostErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/upload/',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
}

export class Orders {
    /**
     * Get Orders
     */
    public static getOrdersApiV1OrdersGet<ThrowOnError extends boolean = false>(options?: Options<GetOrdersApiV1OrdersGetData, ThrowOnError>): RequestResult<GetOrdersApiV1OrdersGetResponses, GetOrdersApiV1OrdersGetErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetOrdersApiV1OrdersGetResponses, GetOrdersApiV1OrdersGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/orders/',
            ...options
        });
    }
}

export class Reports {
    /**
     * Read Reports
     */
    public static readReportsApiV1ReportsGet<ThrowOnError extends boolean = false>(options?: Options<ReadReportsApiV1ReportsGetData, ThrowOnError>): RequestResult<ReadReportsApiV1ReportsGetResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<ReadReportsApiV1ReportsGetResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/',
            ...options
        });
    }
    
    /**
     * Add Report
     */
    public static addReportApiV1ReportsPost<ThrowOnError extends boolean = false>(options: Options<AddReportApiV1ReportsPostData, ThrowOnError>): RequestResult<AddReportApiV1ReportsPostResponses, AddReportApiV1ReportsPostErrors, ThrowOnError> {
        return (options.client ?? client).post<AddReportApiV1ReportsPostResponses, AddReportApiV1ReportsPostErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Remove Report
     */
    public static removeReportApiV1ReportsReportIdDelete<ThrowOnError extends boolean = false>(options: Options<RemoveReportApiV1ReportsReportIdDeleteData, ThrowOnError>): RequestResult<RemoveReportApiV1ReportsReportIdDeleteResponses, RemoveReportApiV1ReportsReportIdDeleteErrors, ThrowOnError> {
        return (options.client ?? client).delete<RemoveReportApiV1ReportsReportIdDeleteResponses, RemoveReportApiV1ReportsReportIdDeleteErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/{report_id}',
            ...options
        });
    }
    
    /**
     * Get Report Id
     */
    public static getReportIdApiV1ReportsReportIdGet<ThrowOnError extends boolean = false>(options: Options<GetReportIdApiV1ReportsReportIdGetData, ThrowOnError>): RequestResult<GetReportIdApiV1ReportsReportIdGetResponses, GetReportIdApiV1ReportsReportIdGetErrors, ThrowOnError> {
        return (options.client ?? client).get<GetReportIdApiV1ReportsReportIdGetResponses, GetReportIdApiV1ReportsReportIdGetErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/{report_id}',
            ...options
        });
    }
}
