// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_loginAccessToken
 */
export type BodyLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_uploadOrders
 */
export type BodyUploadOrders = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CreateReport
 */
export type CreateReport = {
    /**
     * Name
     */
    name: string;
    /**
     * Date Range Start
     */
    date_range_start: string;
    /**
     * Date Range End
     */
    date_range_end: string;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Model Range
     */
    model_range: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OrdersPublic
 */
export type OrdersPublic = {
    /**
     * Order Id
     */
    order_id: number;
    /**
     * Order Date
     */
    order_date: string;
    /**
     * Product Sku
     */
    product_sku: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Price
     */
    price: number;
    /**
     * Qty Ordered
     */
    qty_ordered: number;
    /**
     * Model Range
     */
    model_range: string;
};

/**
 * ReportPublic
 */
export type ReportPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Date Range Start
     */
    date_range_start: string;
    /**
     * Date Range End
     */
    date_range_end: string;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Model Range
     */
    model_range: string;
};

/**
 * ReportPublicWithData
 */
export type ReportPublicWithData = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Date Range Start
     */
    date_range_start: string;
    /**
     * Date Range End
     */
    date_range_end: string;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Model Range
     */
    model_range: string;
    /**
     * Data
     */
    data: Array<OrdersPublic>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginAccessTokenData = {
    body: BodyLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenError = LoginAccessTokenErrors[keyof LoginAccessTokenErrors];

export type LoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenResponse = LoginAccessTokenResponses[keyof LoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type UploadOrdersData = {
    body: BodyUploadOrders;
    path?: never;
    query?: never;
    url: '/api/v1/upload/';
};

export type UploadOrdersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadOrdersError = UploadOrdersErrors[keyof UploadOrdersErrors];

export type UploadOrdersResponses = {
    /**
     * Response Uploadorders
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UploadOrdersResponse = UploadOrdersResponses[keyof UploadOrdersResponses];

export type GetOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start Date
         */
        start_date?: string | null;
        /**
         * End Date
         */
        end_date?: string | null;
        /**
         * Model Range
         */
        model_range?: string | null;
        /**
         * Sku
         */
        sku?: string | null;
    };
    url: '/api/v1/orders/';
};

export type GetOrdersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrdersError = GetOrdersErrors[keyof GetOrdersErrors];

export type GetOrdersResponses = {
    /**
     * Response Getorders
     *
     * Successful Response
     */
    200: Array<OrdersPublic>;
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type GetReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/reports/';
};

export type GetReportsResponses = {
    /**
     * Response Getreports
     *
     * Successful Response
     */
    200: Array<ReportPublic>;
};

export type GetReportsResponse = GetReportsResponses[keyof GetReportsResponses];

export type AddReportData = {
    body: CreateReport;
    path?: never;
    query?: never;
    url: '/api/v1/reports/';
};

export type AddReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddReportError = AddReportErrors[keyof AddReportErrors];

export type AddReportResponses = {
    /**
     * Successful Response
     */
    200: ReportPublic;
};

export type AddReportResponse = AddReportResponses[keyof AddReportResponses];

export type RemoveReportData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}';
};

export type RemoveReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveReportError = RemoveReportErrors[keyof RemoveReportErrors];

export type RemoveReportResponses = {
    /**
     * Response Removereport
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RemoveReportResponse = RemoveReportResponses[keyof RemoveReportResponses];

export type GetReportData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}';
};

export type GetReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportError = GetReportErrors[keyof GetReportErrors];

export type GetReportResponses = {
    /**
     * Successful Response
     */
    200: ReportPublicWithData;
};

export type GetReportResponse = GetReportResponses[keyof GetReportResponses];
