// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_upload_to_db_api_v1_upload__post
 */
export type BodyUploadToDbApiV1UploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CreateReport
 */
export type CreateReport = {
    /**
     * Name
     */
    name: string;
    /**
     * Date Range Start
     */
    date_range_start: string;
    /**
     * Date Range End
     */
    date_range_end: string;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Model Range
     */
    model_range: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Orders
 */
export type Orders = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Order Id
     */
    order_id: number;
    /**
     * Order Date
     */
    order_date: string;
    /**
     * Product Sku
     */
    product_sku: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Price
     */
    price: number;
    /**
     * Qty Ordered
     */
    qty_ordered: number;
    /**
     * Model Range
     */
    model_range: string;
};

/**
 * OrdersPublic
 */
export type OrdersPublic = {
    /**
     * Order Id
     */
    order_id: number;
    /**
     * Order Date
     */
    order_date: string;
    /**
     * Product Sku
     */
    product_sku: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Price
     */
    price: number;
    /**
     * Qty Ordered
     */
    qty_ordered: number;
    /**
     * Model Range
     */
    model_range: string;
};

/**
 * ReportPublic
 */
export type ReportPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Date Range Start
     */
    date_range_start: string;
    /**
     * Date Range End
     */
    date_range_end: string;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Model Range
     */
    model_range: string;
};

/**
 * ReportPublicWithData
 */
export type ReportPublicWithData = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Date Range Start
     */
    date_range_start: string;
    /**
     * Date Range End
     */
    date_range_end: string;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Model Range
     */
    model_range: string;
    /**
     * Data
     */
    data: Array<OrdersPublic>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError = LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type TestTokenApiV1LoginTestTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type TestTokenApiV1LoginTestTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestTokenApiV1LoginTestTokenPostResponse = TestTokenApiV1LoginTestTokenPostResponses[keyof TestTokenApiV1LoginTestTokenPostResponses];

export type UploadToDbApiV1UploadPostData = {
    body: BodyUploadToDbApiV1UploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/upload/';
};

export type UploadToDbApiV1UploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadToDbApiV1UploadPostError = UploadToDbApiV1UploadPostErrors[keyof UploadToDbApiV1UploadPostErrors];

export type UploadToDbApiV1UploadPostResponses = {
    /**
     * Response Upload To Db Api V1 Upload  Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UploadToDbApiV1UploadPostResponse = UploadToDbApiV1UploadPostResponses[keyof UploadToDbApiV1UploadPostResponses];

export type GetOrdersApiV1OrdersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start Date
         */
        start_date?: string | null;
        /**
         * End Date
         */
        end_date?: string | null;
        /**
         * Model Range
         */
        model_range?: string | null;
        /**
         * Sku
         */
        sku?: string | null;
    };
    url: '/api/v1/orders/';
};

export type GetOrdersApiV1OrdersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrdersApiV1OrdersGetError = GetOrdersApiV1OrdersGetErrors[keyof GetOrdersApiV1OrdersGetErrors];

export type GetOrdersApiV1OrdersGetResponses = {
    /**
     * Response Get Orders Api V1 Orders  Get
     *
     * Successful Response
     */
    200: Array<Orders>;
};

export type GetOrdersApiV1OrdersGetResponse = GetOrdersApiV1OrdersGetResponses[keyof GetOrdersApiV1OrdersGetResponses];

export type ReadReportsApiV1ReportsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/reports/';
};

export type ReadReportsApiV1ReportsGetResponses = {
    /**
     * Response Read Reports Api V1 Reports  Get
     *
     * Successful Response
     */
    200: Array<ReportPublic>;
};

export type ReadReportsApiV1ReportsGetResponse = ReadReportsApiV1ReportsGetResponses[keyof ReadReportsApiV1ReportsGetResponses];

export type AddReportApiV1ReportsPostData = {
    body: CreateReport;
    path?: never;
    query?: never;
    url: '/api/v1/reports/';
};

export type AddReportApiV1ReportsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddReportApiV1ReportsPostError = AddReportApiV1ReportsPostErrors[keyof AddReportApiV1ReportsPostErrors];

export type AddReportApiV1ReportsPostResponses = {
    /**
     * Successful Response
     */
    200: ReportPublic;
};

export type AddReportApiV1ReportsPostResponse = AddReportApiV1ReportsPostResponses[keyof AddReportApiV1ReportsPostResponses];

export type RemoveReportApiV1ReportsReportIdDeleteData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}';
};

export type RemoveReportApiV1ReportsReportIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveReportApiV1ReportsReportIdDeleteError = RemoveReportApiV1ReportsReportIdDeleteErrors[keyof RemoveReportApiV1ReportsReportIdDeleteErrors];

export type RemoveReportApiV1ReportsReportIdDeleteResponses = {
    /**
     * Response Remove Report Api V1 Reports  Report Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RemoveReportApiV1ReportsReportIdDeleteResponse = RemoveReportApiV1ReportsReportIdDeleteResponses[keyof RemoveReportApiV1ReportsReportIdDeleteResponses];

export type GetReportIdApiV1ReportsReportIdGetData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}';
};

export type GetReportIdApiV1ReportsReportIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportIdApiV1ReportsReportIdGetError = GetReportIdApiV1ReportsReportIdGetErrors[keyof GetReportIdApiV1ReportsReportIdGetErrors];

export type GetReportIdApiV1ReportsReportIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReportPublicWithData;
};

export type GetReportIdApiV1ReportsReportIdGetResponse = GetReportIdApiV1ReportsReportIdGetResponses[keyof GetReportIdApiV1ReportsReportIdGetResponses];
