// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AddReportData, AddReportErrors, AddReportResponses, GetOrdersData, GetOrdersErrors, GetOrdersResponses, GetReportData, GetReportErrors, GetReportResponses, GetReportsData, GetReportsResponses, LoginAccessTokenData, LoginAccessTokenErrors, LoginAccessTokenResponses, LoginTestTokenData, LoginTestTokenResponses, RemoveReportData, RemoveReportErrors, RemoveReportResponses, UploadOrdersData, UploadOrdersErrors, UploadOrdersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Login {
    /**
     * Login Access Token
     */
    public static loginAccessToken<ThrowOnError extends boolean = false>(options: Options<LoginAccessTokenData, ThrowOnError>): RequestResult<LoginAccessTokenResponses, LoginAccessTokenErrors, ThrowOnError> {
        return (options.client ?? client).post<LoginAccessTokenResponses, LoginAccessTokenErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Test Token
     */
    public static loginTestToken<ThrowOnError extends boolean = false>(options?: Options<LoginTestTokenData, ThrowOnError>): RequestResult<LoginTestTokenResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).post<LoginTestTokenResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/login/test-token',
            ...options
        });
    }
}

export class Upload {
    /**
     * Upload To Db
     */
    public static uploadOrders<ThrowOnError extends boolean = false>(options: Options<UploadOrdersData, ThrowOnError>): RequestResult<UploadOrdersResponses, UploadOrdersErrors, ThrowOnError> {
        return (options.client ?? client).post<UploadOrdersResponses, UploadOrdersErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/upload/',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
}

export class Orders {
    /**
     * Get Orders
     */
    public static getOrders<ThrowOnError extends boolean = false>(options?: Options<GetOrdersData, ThrowOnError>): RequestResult<GetOrdersResponses, GetOrdersErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetOrdersResponses, GetOrdersErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/orders/',
            ...options
        });
    }
}

export class Reports {
    /**
     * Read Reports
     */
    public static getReports<ThrowOnError extends boolean = false>(options?: Options<GetReportsData, ThrowOnError>): RequestResult<GetReportsResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<GetReportsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/',
            ...options
        });
    }
    
    /**
     * Add Report
     */
    public static addReport<ThrowOnError extends boolean = false>(options: Options<AddReportData, ThrowOnError>): RequestResult<AddReportResponses, AddReportErrors, ThrowOnError> {
        return (options.client ?? client).post<AddReportResponses, AddReportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Remove Report
     */
    public static removeReport<ThrowOnError extends boolean = false>(options: Options<RemoveReportData, ThrowOnError>): RequestResult<RemoveReportResponses, RemoveReportErrors, ThrowOnError> {
        return (options.client ?? client).delete<RemoveReportResponses, RemoveReportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/{report_id}',
            ...options
        });
    }
    
    /**
     * Get Report Id
     */
    public static getReport<ThrowOnError extends boolean = false>(options: Options<GetReportData, ThrowOnError>): RequestResult<GetReportResponses, GetReportErrors, ThrowOnError> {
        return (options.client ?? client).get<GetReportResponses, GetReportErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/reports/{report_id}',
            ...options
        });
    }
}
